<center> <h1> Google Maps API </h> </center> 
<center> <h2> Homework 1 </h> </center> 
<center> <h3> Data Preprocessing </h> </center>

A. Use the [*Nearby Seach*](https://developers.google.com/places/web-service/search) Method to find all the restaurant near to the UPY (20.988459, -89.736768) around 2km. In order to fulfill this item you need to:
* Create a *search_nearby_places* function with the appropiate parameters. It must return a JSON with the results. Places must be ranked by distance.
* Create a table with the following columns: Name, Place Id, Rating, Place Types, Total of User Ratings.

In [3]:
import pandas as pd
import json
import requests
import time

In [36]:
"""Find and return all the nearby restaurants from a given place.

The following function uses the Google Maps Places API to obtain and return all the restaurants that are in a given range, from a given point.
This function could also look for other than restaurants, however that would require to modify the API link (type = kind of places).

  Typical usage example:

  search_nearby_places(latitude, longitude, radius of search, API key), where:
      -Latitude and longitude refer to the ubication of the place we are taking as base. It is possible to find them from the Google Maps App (INTEGERS).
      -Radius of search is the radius of the circle in which we are looking for Restaurants, with origin at the place we select (INTEGER).
      -API key is our Google Maps Cloud Services key, it is not required to pay for it but you need to register in order to obtain it (STRING).
"""

def search_nearby_places(lat, lon, radius, key):
    data = json.loads(requests.get('https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={},{}&radius={}&key={}&type=restaurant'.format(lat, lon, radius, key)).content)
    df = pd.DataFrame(data['results'])
    df = df.drop(['geometry', 'icon', 'id', 'opening_hours', 'photos', 'plus_code', 'reference', 'scope', 'vicinity'], axis = 1)
    return df

search_nearby_places(20.988459, -89.736768, 2000, 'API KEY HERE').head()

,name,place_id,rating,types,user_ratings_total
0,La Glorieta (Cocina y Pizzería),ChIJC9i7XEsNVo8Ro2-sdS45rBg,4.1,"[restaurant, food, point_of_interest, establis...",14.0
1,Mr. Cazuelas,ChIJ3WHHeJkMVo8RO_z2pfoDFZg,4.0,"[restaurant, food, point_of_interest, establis...",3.0
2,El Rincón Del Tabas,ChIJn4UFHpwMVo8RZOfFHQCuIwo,5.0,"[restaurant, food, point_of_interest, establis...",2.0
3,Moyoyos burger,ChIJqxQ91h0NVo8R52sc8a1HlvE,NaN,"[restaurant, food, point_of_interest, establis...",NaN
4,"Cocina economica ""El sabor de doña antonia""",ChIJaQJm928NVo8RAN8mnDmvYEk,NaN,"[restaurant, food, point_of_interest, establis...",NaN

B. Create a function to Find the Place Id given Place Name (String) and Location (Lat/Lont Tuple).

In [20]:
"""Find the Google Maps ID of a given place.

This function uses the location data (name of the place, latitude and longitude) to find its ID.
The ID of the place is the unique number of identification provided by Google Maps.

  Typical usage example:

  placefinder(name of the place, location, API key), where:
      -Name of the place is literally the name. Quotation marks should be deleted. (STRING)
      -The location must be written as a tuple of latitude and longitude, for example: (20.999, -80.999). (INTEGERS - TUPLE)
      -API key is our Google Maps Cloud Services key, it is not required to pay for it but you need to register in order to obtain it (STRING).
"""

def placefinder(place, location, key):
    placedata = json.loads(requests.get('https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input={}&inputtype=textquery&locationbias={},{}&key={}'.format(place, location[0], location[1], key)).content)
    placeid = placedata['candidates'][0]['place_id']
    return placeid

C. Find the Place ID of the following places using your functions:
* McCarthy's Irish Pub - Caucel
* Starbucks Montejo
* Los Trompos Circuito

In [19]:
print("McCarthy's Caucel ID is:", placefinder('McCarthys Irish Pub - Caucel', (21.000164, -89.682518), 'API KEY HERE'), '\n')
print("Starbucks Montejo ID is:", placefinder('Starbucks Montejo', (20.985224, -89.618220), 'API KEY HERE'), '\n')
print("Los Trompos Circuito ID is:", placefinder('Los Trompos Circuito', (20.998820,  -89.617421), 'API KEY HERE'), '\n')

McCarthy's Caucel ID is: ChIJJyKKOKB0Vo8RCQcxkUw6hp8

Starbucks Montejo ID is: ChIJaUUfylFxVo8RgEGjoansPbc

Los Trompos Circuito ID is: ChIJRwkizrxxVo8R1EULFLWZ2JQ

D. Use the [*Place Details*](https://developers.google.com/places/web-service/details#PlaceDetailsResults) Method to find the Reviews of a Place in English and Spanish. In order to fulfill this item you need to:
* Create a *find_reviews* function with the appropiate parameters. It must return a JSON with the results. 
* Create a table with the following columns: Author Name, Language, Rating, Text, Time.

In [33]:
"""Find Google Maps reviews from a given place.

This function uses the ID from a given place (which can be obtained with the previous function) and our prefered language to find reviews.

  Typical usage example:

  find_reviews(place ID, language, API key), where:
      -Place ID refers to the Google Maps identification number of the place we are looking for (STRING).
      -Language refers to the abbreviation of the reviews' language we are looking for (English = en, Spanish = es) (STRING, separeted by commas).
      -API key is our Google Maps Cloud Services key, it is not required to pay for it but you need to register in order to obtain it (STRING).
"""

def find_reviews(placeid, language, key):
    reviewsdata = json.loads(requests.get('https://maps.googleapis.com/maps/api/place/details/json?place_id={}&language={}&key={}'.format(placeid, language, key)).content)
    placereviews = pd.DataFrame(reviewsdata['result']['reviews'])
    placereviews = placereviews.drop(['author_url', 'profile_photo_url', 'relative_time_description'], axis = 1)
    return placereviews

In [34]:
#Reviews of Starbucks Montejo.
find_reviews('ChIJaUUfylFxVo8RgEGjoansPbc', 'es,en', 'API KEY HERE')

,author_name,language,rating,text,time
0,Brandy Campbell,en,5,They are always so fast and very polite. I'm a...,1558744858
1,J T,en,4,Lovely place. Good service. I have one request...,1543268696
2,Amy King,en,4,Lots of space in this two story starbucks,1560620959
3,James Wilson,en,3,I am Canadian and rarely visit Starbucks anywh...,1544219879
4,Carlos G,en,1,This Starbucks S..CKS...!!!!... the worst coff...,1547604761

E. Find similar places to Los Trompos Circuito. Rank them by its "Prominence". In order to fulfill this item you need to:
* Create a *find_similar* function with the appropiate parameters. It must return a JSON with the results.
* Create a table with the following columns: Place Name, Plaece Id, Rating, Total of Use Ratings.

In [38]:
"""Find places similar to a given place.

This function uses the location of a given place in order to find similar places, based on the "Prominence" or the popularity of the places.

  Typical usage example:

  find_similar(latitude, longitude, radius of search, API key), where:
      -Latitude and Longitude both refer to the location of the place. The info can be obtained from the Google Maps App (2 Integers - NOT a tuple).
      -Radius of search is the radius of the circle in which we are looking for Restaurants, with origin at the place we select (INTEGER).
      -API key is our Google Maps Cloud Services key, it is not required to pay for it but you need to register in order to obtain it (STRING).
"""
#Prominence = Popularity = Number of reviews. 
#Los Trompos Circuito Data:
#Lat: 20.998820
#Lon: -89.617421

def find_similar(lat, lon, radius, key):
    place = json.loads(requests.get('https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={},{}&radius={}&key={}&type=restaurant'.format(lat, lon, radius, key)).content)
    placeinfo = pd.DataFrame(place['results'])
    placeinfo = placeinfo.drop(['geometry', 'icon', 'id', 'photos', 'plus_code', 'reference', 'scope', 'opening_hours', 'price_level', 'types', 'vicinity'], axis = 1)
    placeinfo = placeinfo.sort_values('user_ratings_total', ascending = False)
    return placeinfo
find_similar(20.998820, -89.617421, 2000, 'API KEY HERE').head()

,name,place_id,rating,user_ratings_total
13,Mr. Pampas,ChIJE1CvhrJ2Vo8RF6OCmqVdXjU,4.6,3970.0
10,Los Trompos,ChIJpVKXOq12Vo8RK4bUWILT9dI,4.5,3161.0
4,Eladio's,ChIJ9yoFwm5xVo8Rppx5yDFu_oQ,4.5,2099.0
12,Pizza del Perro Negro,ChIJS67Ey6x2Vo8RTiTblDl7VT0,4.4,1823.0
17,BBT,ChIJ32PLn7R2Vo8Rr1TsvQkbBrY,4.1,1626.0

F. Complete all the above tasks but using the Python [GoogleMaps](https://github.com/googlemaps/google-maps-services-python) Library. [Here](https://googlemaps.github.io/google-maps-services-python/docs/#module-googlemaps) you can find the documentation.

In [39]:
import googlemaps
import pandas as pd
maps = googlemaps.Client(key='API KEY HERE')

In [40]:
#A. Use the [*Nearby Seach*] Method to find all the restaurant near to the UPY (20.988459, -89.736768) around 2km. In order to fulfill this item you need to:

"""Find and return all the nearby restaurants from a given place.

The following function uses the Google Maps Python API to obtain and return all places near to a given place.

  Typical usage example:

  places_nearby(location = (lat, lon), radius = (radius), type = ('type of place')), where:
      -Latitude and longitude refer to the ubication of the place we are taking as base. It is possible to find them from the Google Maps App (INTEGERS, TUPLE).
      -Radius of search is the radius of the circle in which we are looking for Restaurants, with origin at the place we select (INTEGER).
      -Type is the kind of place we are looking for. A full list of types of places can be find at Google Maps API website (STRING).
"""

places_near = maps.places_nearby(location=(20.988459, -89.736768), radius=2000, type='restaurant')
places_near = pd.DataFrame(places_near['results'])
places_near = places_near.drop(['geometry', 'icon', 'id', 'opening_hours', 'photos', 'plus_code', 'reference', 'scope', 'vicinity'], axis = 1)
places_near.head()

,name,place_id,rating,types,user_ratings_total
0,La Glorieta (Cocina y Pizzería),ChIJC9i7XEsNVo8Ro2-sdS45rBg,4.1,"[restaurant, food, point_of_interest, establis...",14.0
1,Mr. Cazuelas,ChIJ3WHHeJkMVo8RO_z2pfoDFZg,4.0,"[restaurant, food, point_of_interest, establis...",3.0
2,El Rincón Del Tabas,ChIJn4UFHpwMVo8RZOfFHQCuIwo,5.0,"[restaurant, food, point_of_interest, establis...",2.0
3,Moyoyos burger,ChIJqxQ91h0NVo8R52sc8a1HlvE,NaN,"[restaurant, food, point_of_interest, establis...",NaN
4,"Cocina economica ""El sabor de doña antonia""",ChIJaQJm928NVo8RAN8mnDmvYEk,NaN,"[restaurant, food, point_of_interest, establis...",NaN

In [41]:
#B. Create a function to Find the Place Id given Place Name (String) and Location (Lat/Lont Tuple).

"""Find the Google Maps ID of a given place.

This function uses the name of a place and its location (latitude and longitude) to find its Google Maps ID

  Typical usage example:

  find_id(name of the place, location(lat, lon)), where:
      -Name of the place is literally the name. Quotation marks should be deleted. (STRING)
      -The location must be written as a tuple of latitude and longitude, for example: (20.999, -80.999). (ONE SINGLE STRING, separated by commas).
"""

def find_id(inputname, location):
    find = maps.find_place(input = inputname, location_bias = 'circle:200@' + location, input_type = 'textquery')
    find = find['candidates'][0]['place_id']
    return (print("The ID of '", inputname, "' is:", find))

In [42]:
#C. Find the Place ID of the following places using your functions:
#   -McCarthy's Irish Pub - Caucel ---- 21.000164, -89.682518
#   -Starbucks Montejo ---------------- 20.985224, -89.618220
#   -Los Trompos Circuito ------------- 21.000130, -89.617245
find_id('McCarthys Irish Pub - Caucel', '21.000164, -89.682518')
find_id('Starbucks Montejo', '20.985224, -89.618220')
find_id('Los Trompos Circuito', '21.000130, -89.617245')

The ID of ' McCarthys Irish Pub - Caucel ' is: ChIJJyKKOKB0Vo8RCQcxkUw6hp8
The ID of ' Starbucks Montejo ' is: ChIJaUUfylFxVo8RgEGjoansPbc
The ID of ' Los Trompos Circuito ' is: ChIJpVKXOq12Vo8RK4bUWILT9dI

In [14]:
#D. Use the [*Place Details*] Method to find the Reviews of a Place in English and Spanish. In order to fulfill this item you need to:
#* Create a *find_reviews* function with the appropiate parameters. It must return a JSON with the results. 
#* Create a table with the following columns: Author Name, Language, Rating, Text, Time.

"""Find Google Maps reviews from a given place.

This function uses the ID from a given place (which can be obtained with the previous function) to find reviews in English and Spanish.

  Typical usage example:

  find_reviews(place ID), where:
      -Place ID refers to the Google Maps identification number of the place we are looking for (STRING).
"""

import pandas as pd
import json
def find_reviews(placeid):
    reviews = maps.place(place_id = placeid, language='en,es')
    reviews = pd.read_json(json.dumps(reviews['result']['reviews']), orient='records')
    reviews = reviews.drop(['author_url', 'profile_photo_url', 'relative_time_description'], axis = 1)
    return reviews
find_reviews('ChIJaUUfylFxVo8RgEGjoansPbc')

,author_name,language,rating,text,time
0,Brandy Campbell,en,5,They are always so fast and very polite. I'm a...,1558744858
1,J T,en,4,Lovely place. Good service. I have one request...,1543268696
2,Amy King,en,4,Lots of space in this two story starbucks,1560620959
3,James Wilson,en,3,I am Canadian and rarely visit Starbucks anywh...,1544219879
4,Carlos G,en,1,This Starbucks S..CKS...!!!!... the worst coff...,1547604761

In [43]:
#E. Find similar places to Los Trompos Circuito. Rank them by its "Prominence". In order to fulfill this item you need to:
#* Create a *find_similar* function with the appropiate parameters. It must return a JSON with the results.
#* Create a table with the following columns: Place Name, Plaece Id, Rating, Total of Use Ratings.

"""Find places similar to a given place.

This function uses the location of a given place in order to find similar places, based on the "Prominence" or the popularity of the places.

  Typical usage example:

  find_similar((latitude, longitude)), where:
      -Latitude and Longitude both refer to the location of the place. The info can be obtained from the Google Maps App (2 Integers Tuple - STRING).
"""

def find_similar(locatn):
    similar = maps.places_nearby(location = locatn, radius=1000, type='restaurant', rank_by='prominence')
    similar = pd.read_json(json.dumps(similar['results']), orient='records')
    similar = similar[['name', 'id', 'rating', 'user_ratings_total']]
    return similar
find_similar('21.000130, -89.617245').head()

,name,id,rating,user_ratings_total
0,La Parrilla | Paseo Montejo,60529df458f797c3088c99df06af34a72ad02653,4.1,1185.0
1,Muelle 8,55002d724777102571b5593739204d4fe41c1d32,4.5,200.0
2,Los Trompos,cf6c67c9eb44c578189fe7afa775b9c87026672f,4.5,3161.0
3,Mi Viejo Molino,0525209b56b3dfac93492825024c73986cb1c704,4.2,1401.0
4,Mr. Pampas,657620905f41cddeeefd73c87f0038e76d1320b9,4.6,3970.0

G. Create a Github Project as a Tutorial about How to Use the Google API. Don't forget to include a section with the set of instructions to obtain the Google API Key. In this tutorial, compare the use of the Google Maps [Places API] (https://developers.google.com/places/web-service/intro) and the Python [GoogleMaps](https://github.com/googlemaps/google-maps-services-python) Library using this activity tasks as examples.

## Checklist

| Task | Points |
|:----:|:------:|
|   Class Participation  |   10   |
|   a  |   10   |
|   b  |   10   |
|   c  |   10   |
|   d  |   10   |
|   e  |   10   |
|   f  |   20   |
|   g  |   20   |


* **Important!** Partial credit can be obteined in each task.
* Don not forget to document your functions! [Here](http://google.github.io/styleguide/pyguide.html) is the Python Programming Styleguide from Google. [Section 3.8](http://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings) is about Comments and Docstrings.
* To obtain the Class Participation Score you must complete an early submission with tasks: A, B and C.